version: '3'

services:
  broker:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "user_mq"
      RABBITMQ_DEFAULT_PASS: "RabbitMQ2019!"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - messaging
  database:
    image: 'microsoft/mssql-server-linux'
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: "Secret1234"
      ACCEPT_EULA: "Y"

networks: 
    messaging:
      driver: bridge