version: '3'

services:
  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
    networks:
      - messaging
  database:
    image: 'microsoft/mssql-server-linux'
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: "Secret1234"
      ACCEPT_EULA: "Y"
    networks:
      - messaging
networks: 
    messaging:
      driver: bridge